// ---Auto Generated by Only4Play ---
package org.iyo.codegen.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import lombok.Data;

@Schema
@Data
public class UserDTO {
  @Schema(
      title = "serialVersionUID"
  )
  private long serialVersionUID;

  @Schema(
      title = "id"
  )
  private Integer id;

  @Schema(
      title = "userName"
  )
  private String userName;

  @Schema(
      title = "age"
  )
  private Integer age;

  protected UserDTO() {
  }

  public long getSerialVersionUID() {
    return serialVersionUID;
  }

  public void setSerialVersionUID(long serialVersionUID) {
    this.serialVersionUID = serialVersionUID;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }
}
